### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by dxil** [daruk-framework/daruk.org#1]
![cpu](https://user-images.githubusercontent.com/17681925/54181318-22908780-44d9-11e9-8fd7-fdbd58ef26f2.png)
![内存](https://user-images.githubusercontent.com/17681925/54181325-26bca500-44d9-11e9-932b-b50f16307252.jpg)

**Comment by xiaojue** [comment]
其实根本不用发出来的，直接贴地址就行了。😂。
